define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    
    // FilePicker strings
    "PageTitle": "FilePicker Control Demo",
    "PageDescription": "This sample demonstrates various configurations of the FilePicker control from the PnP reusable React controls library. Each example below shows a different use case and configuration option.",
    "FilePickerLabel": "Select a file",
    "FilePickerButtonLabel": "Browse Files",
    "SelectedFileLabel": "Selected File Information",
    "NoFileSelectedMessage": "No file has been selected yet. Click the button above to select a file.",
    "FileNameLabel": "File Name",
    "FileUrlLabel": "File URL",
    "FileSizeLabel": "File Size",
    "DownloadFileLabel": "Download File Content",
    "ClearSelectionLabel": "Clear Selection",
    "FilePickerDescription": "Use the button below to browse and select files from various sources including Site Libraries, OneDrive, Recent Files, Upload, and more.",
    "BytesLabel": "bytes",
    
    // Example sections
    "Example1Title": "Minimal Configuration",
    "Example1Description": "This example shows the minimal required properties to use the FilePicker control: label, onSave, and context.",
    "Example2Title": "Custom Button Icon",
    "Example2Description": "Using buttonIcon property to display an icon button instead of a text button. Also demonstrates buttonIconProps for additional customization.",
    "Example3Title": "onChange Handler",
    "Example3Description": "The onChange handler is triggered whenever the file selection changes, even before saving. Useful for real-time validation.",
    "Example4Title": "onCancel Handler",
    "Example4Description": "The onCancel handler is called when the user closes the FilePicker panel without selecting a file.",
    "Example5Title": "File Type Restrictions",
    "Example5Description": "Using the accepts property to restrict file selection to specific types. This example only allows .docx and .pdf files.",
    "Example6Title": "Required Field",
    "Example6Description": "The required property adds visual indication that a file selection is mandatory.",
    "Example7Title": "Disabled State",
    "Example7Description": "The disabled property prevents user interaction with the FilePicker control.",
    "Example8Title": "Hidden Control",
    "Example8Description": "The hidden property allows you to hide the picker button while still controlling panel visibility programmatically via isPanelOpen.",
    "Example9Title": "Check If File Exists",
    "Example9Description": "When using file links, the checkIfFileExists property validates that the linked file actually exists.",
    "Example10Title": "Tab Visibility Control",
    "Example10Description": "Use the toggles below to show or hide specific tabs in the FilePicker. This demonstrates the hide properties like hideRecentTab, hideOneDriveTab, etc.",
    
    // Additional labels
    "SelectFile": "Select a file",
    "PickDocument": "Pick Document",
    "FileChangedMessage": "File selection changed!",
    "FileCancelledMessage": "File picker was cancelled",
    "OnlyDocxPdfLabel": "Select document (DOCX or PDF only)",
    "RequiredFileLabel": "Select a required file",
    "DisabledPickerLabel": "Disabled file picker",
    "HiddenPickerLabel": "Hidden file picker (controlled programmatically)",
    "ToggleVisibilityButton": "Toggle Picker Visibility",
    "ShowPicker": "Show",
    "HidePicker": "Hide",
    "CheckFileExistsLabel": "Select file with validation",
    "TabVisibilityLabel": "Control tab visibility",
    "TabVisibilityDescription": "Toggle the switches below to show/hide specific tabs",
    "HideRecentTab": "Hide Recent Tab",
    "HideWebSearchTab": "Hide Web Search Tab",
    "HideStockImages": "Hide Stock Images Tab",
    "HideOrganisationalAssetTab": "Hide Organisational Asset Tab",
    "HideOneDriveTab": "Hide OneDrive Tab",
    "HideSiteFilesTab": "Hide Site Files Tab",
    "HideLocalUploadTab": "Hide Local Upload Tab",
    "HideLocalMultipleUploadTab": "Hide Multiple Upload Tab",
    "HideLinkUploadTab": "Hide Link Upload Tab"
  }
});