const gridItems = [
	{
		thumbnail: "https://picsum.photos/200/150?random=1",
		title: "Adventures in SPFx",
		name: "Perry Losselyong",
		profileImageSrc: "https://i.pravatar.cc/50?img=1",
		location: "SharePoint",
		activity: "3/13/2024",
	},
	{
		thumbnail: "https://picsum.photos/200/150?random=2",
		title: "The Wild, Untold Story of SharePoint!",
		name: "Ebonee Gallyhaock",
		profileImageSrc: "https://i.pravatar.cc/50?img=2",
		location: "SharePoint",
		activity: "6/29/2024",
	},
	{
		thumbnail: "https://picsum.photos/200/150?random=3",
		title: "Low Code Solutions: PowerApps",
		name: "Seward Keith",
		profileImageSrc: "https://i.pravatar.cc/50?img=3",
		location: "PowerApps",
		activity: "12/31/2023",
	},
	{
		thumbnail: "https://picsum.photos/200/150?random=4",
		title: "Not Your Grandpa's SharePoint",
		name: "Sharona Selkirk",
		profileImageSrc: "https://i.pravatar.cc/50?img=4",
		location: "SharePoint",
		activity: "11/20/2023",
	},
	{
		thumbnail: "https://picsum.photos/200/150?random=5",
		title: "Get with the Flow",
		name: "Boyce Batstone",
		profileImageSrc: "https://i.pravatar.cc/50?img=5",
		location: "Flow",
		activity: "5/26/2024",
	},
	{
		thumbnail: "https://picsum.photos/200/150?random=6",
		title: "Modern Workplace Transformation",
		name: "Alice Johnson",
		profileImageSrc: "https://i.pravatar.cc/50?img=6",
		location: "Microsoft 365",
		activity: "1/15/2024",
	},
	{
		thumbnail: "https://picsum.photos/200/150?random=7",
		title: "Teams Development Best Practices",
		name: "Bob Smith",
		profileImageSrc: "https://i.pravatar.cc/50?img=7",
		location: "Teams",
		activity: "4/22/2024",
	},
	{
		thumbnail: "https://picsum.photos/200/150?random=8",
		title: "Power Platform Integration Patterns",
		name: "Carol White",
		profileImageSrc: "https://i.pravatar.cc/50?img=8",
		location: "Power Platform",
		activity: "8/10/2024",
	}
];
export default gridItems;
